### ISSUE TITLE
Failure when trying to use in new project

### ISSUE THREAD

**Issue by facultymatt** [neilmendoza/ofxMovieExporter#4]
The library works great when running the example. When I try to include the library in a new project, I get the following error when compiling:

```
"libavutil/samplefmt.h" file not found
```

Any idea how to resolve this?

**Comment by facultymatt** [comment]
Figured it out - I needed to modify the project's header search path list, adding the following: `"../../../addons/ofxMovieExporter/libs/libav/include/"`

Find the list by clicking on the project build settings, then scrolling down to `header search paths`: 
![screen shot 2014-03-01 at 8 30 51 am](https://f.cloud.github.com/assets/1406258/2301457/f21e7292-a145-11e3-9b44-865d65b08a70.png)

Click on the value which will open a panel where you should add this value: 
![screen shot 2014-03-01 at 8 30 40 am](https://f.cloud.github.com/assets/1406258/2301458/f49eeede-a145-11e3-97ab-7228b1d2384e.png)

**Comment by neilmendoza** [comment]
Glad you figured it out.  Did you use the project generator to create the project you were using it for?

**Comment by facultymatt** [comment]
No I didn't use the project generator. I added it to an existing project so the generator wasn't an option. I was unaware of the need to modify build settings to include the libs. Might be worth adding to the readme. :)—
